EmailAccountDescription: {{ account.get('description', account.address) }}
EmailAccountType: {{ account_types[account.get('type', 'imap')] }}
EmailAccountName: {{ account.get('name', account.address.split('@')[0]) }}
EmailAddress: {{ account.address }}
IncomingMailServerAuthentication: {{ auth_types[account.server_in.get('auth', 'password')] }}
IncomingMailServerHostName: {{ account.server_in.domain }}
IncomingMailServerPortNumber: {{ account.server_in.get('port', 993) }}
IncomingMailServerUseSSL:  {{ account.server_in.get('ssl', True) | to_bool }}
IncomingMailServerUsername: {{ account.server_in.get('username', account.address) }}
OutgoingMailServerAuthentication: {{ auth_types[account.server_out.get('auth', 'password')] }}
OutgoingMailServerHostName: {{ account.server_out.domain }}
OutgoingMailServerPortNumber: {{ account.server_out.get('port', 465) }}
OutgoingMailServerUseSSL:  {{ account.server_out.get('ssl', True) | to_bool }}
OutgoingMailServerUsername: {{ account.server_out.get('username', account.address) }}
OutgoingPasswordSameAsIncomingPassword: {{ account.server_out.get('password_sameas_in', True) | to_bool }}
PayloadDescription: Configures email account.
PayloadDisplayName: IMAP Account ({{ account.address }})
PreventAppSheet: false
PreventMove: false
SMIMESigningUserOverrideable: true
SMIMESigningCertificateUUIDUserOverrideable: true
SMIMEEncryptByDefaultUserOverrideable: true
SMIMEEncryptionCertificateUUIDUserOverrideable: true
SMIMEEnableEncryptionPerMessageSwitch: true
