# vim: ft=yaml
---
###############################################################################
# Define all YAML node anchors
###############################################################################
.node_anchors:
  # `only` (also used for `except` where applicable)
  only_branch_master_parent_repo: &only_branch_master_parent_repo
    - 'master@lkubb/salt-tool-macos-formula'
  # `stage`
  stage_lint: &stage_lint 'lint'
  stage_release: &stage_release 'release'
  # `image`
  image_commitlint: &image_commitlint 'myii/ssf-commitlint:11'
  image_dindruby: &image_dindruby 'dafyddj/ci-dind-python-ruby:2.0.2'
  image_dindrubybionic: &image_dindrubybionic 'dafyddj/ci-dind-python-ruby:2.0.2'
  image_precommit: &image_precommit 'dafyddj/ci-pre-commit:2.1.0'
  image_rubocop: &image_rubocop 'pipelinecomponents/rubocop:latest'
  image_semantic-release: &image_semanticrelease 'myii/ssf-semantic-release:15.14'
  # `services`
  services_docker_dind: &services_docker_dind
    - 'docker:dind'
  # `variables`
  # https://forum.gitlab.com/t/gitlab-com-ci-caching-rubygems/5627/3
  # https://bundler.io/v1.16/bundle_config.html
  variables_bundler: &variables_bundler
    BUNDLE_CACHE_PATH: '${CI_PROJECT_DIR}/.cache/bundler'
    BUNDLE_WITHOUT: 'production'
  # `cache`
  cache_bundler: &cache_bundler
    key: '${CI_JOB_STAGE}'
    paths:
      - '${BUNDLE_CACHE_PATH}'

###############################################################################
# Define stages and global variables
###############################################################################
stages:
  - *stage_lint
  - *stage_release
variables:
  DOCKER_DRIVER: 'overlay2'

###############################################################################
# `lint` stage: `commitlint`, `pre-commit` & `rubocop` (latest, failure allowed)
###############################################################################
commitlint:
  stage: *stage_lint
  image: *image_commitlint
  script:
    # Add `upstream` remote to get access to `upstream/master`
    - 'git remote add upstream
       https://gitlab.com/lkubb/salt-tool-macos-formula.git'
    - 'git fetch --all'
    # Set default commit hashes for `--from` and `--to`
    - 'export COMMITLINT_FROM="$(git merge-base upstream/master HEAD)"'
    - 'export COMMITLINT_TO="${CI_COMMIT_SHA}"'
    # `coqbot` adds a merge commit to test PRs on top of the latest commit in
    # the repo; amend this merge commit message to avoid failure
    - |
      if [ "${GITLAB_USER_LOGIN}" = "coqbot" ] \
      && [ "${CI_COMMIT_BRANCH}" != "master" ]; then
        git commit --amend -m \
          'chore: reword coqbot merge commit message for commitlint'
        export COMMITLINT_TO=HEAD
      fi
    # Run `commitlint`
    - 'commitlint --from "${COMMITLINT_FROM}"
                  --to   "${COMMITLINT_TO}"
                  --verbose'

pre-commit:
  stage: *stage_lint
  image: *image_precommit
  # https://pre-commit.com/#gitlab-ci-example
  variables:
    PRE_COMMIT_HOME: '${CI_PROJECT_DIR}/.cache/pre-commit'
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - '${PRE_COMMIT_HOME}'
  script:
    - 'pre-commit run --all-files --color always --verbose'

# Use a separate job for `rubocop` other than the one potentially run by `pre-commit`
# - The `pre-commit` check will only be available for formulas that pass the default
#   `rubocop` check -- and must continue to do so
# - This job is allowed to fail, so can be used for all formulas
# - Furthermore, this job uses all of the latest `rubocop` features & cops,
#   which will help when upgrading the `rubocop` linter used in `pre-commit`
rubocop:
  allow_failure: true
  stage: *stage_lint
  image: *image_rubocop
  script:
    - 'rubocop -d -P -S --enable-pending-cops'

###############################################################################
# `release` stage: `semantic-release`
###############################################################################
semantic-release:
  only: *only_branch_master_parent_repo
  stage: *stage_release
  image: *image_semanticrelease
  variables:
    MAINTAINER_TOKEN: '${GH_TOKEN}'
  script:
    # Update `AUTHORS.md`
    - '${HOME}/go/bin/maintainer contributor'
    # Run `semantic-release`
    - 'semantic-release'
