# vim: ft=yaml
---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: |
    ci(pre-commit.ci): apply auto fixes from pre-commit.com hooks

    For more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: |
    ci(pre-commit.ci): perform `pre-commit` autoupdate
  autoupdate_schedule: quarterly
  skip: []
  submodules: false
default_stages: [commit]
repos:
  - repo: https://github.com/dafyddj/commitlint-pre-commit-hook
    rev: v2.3.0
    hooks:
      - id: commitlint
        name: Check commit message using commitlint
        description: Lint commit message against @commitlint/config-conventional rules
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional@17.1.0']
  - repo: https://github.com/rubocop-hq/rubocop
    rev: v1.57.0
    hooks:
      - id: rubocop
        name: Check Ruby files with rubocop
        args: [--debug]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        name: Check shell scripts with shellcheck
        files: ^.*\.(sh|bash|ksh)$
        types: []
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: Check YAML syntax with yamllint
        args: [--strict]
        types: [file]
        # Files to include
        # 1. Obvious YAML files
        # 2. `pillar.example` and similar files
        # 3. SLS files under directory `test/` which are pillar files
        # Files to exclude
        # 1. SLS files under directory `test/` which are state files
        # 2. `kitchen.vagrant.yml`, which contains Embedded Ruby (ERB) template syntax
        # 3. YAML files heavily reliant on Jinja
        files: |
          (?x)^(
                .*\.yaml|
                .*\.yml|
                \.salt-lint|
                \.yamllint|
                .*\.example|
                test/.*\.sls
          )$
        exclude: |
          (?x)^(
                kitchen.vagrant.yml|
                test/.*/states/.*\.sls|
                pillar.example
          )$
  - repo: https://github.com/warpnet/salt-lint
    rev: v0.9.2
    hooks:
      - id: salt-lint
        name: Check Salt files using salt-lint
        files: ^.*\.(sls|jinja|j2|tmpl|tst)$
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: ['toml']
        files: >
          (?x)(
            _modules/.*|
            _states/.*
          )
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: blacken Python code
        files: >
          (?x)(
            _modules/.*|
            _states/.*
          )
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        name: Run bandit against modules
        args: [--silent, -lll]
        files: >
          (?x)(
            _modules/.*|
            _states/.*
          )
  - repo: local
    hooks:
      - id: slsdoc
        name: Dump state documentation with slsdoc
        entry: ./bin/slsdoc
        language: system
        require_serial: true
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: render_readme
        name: Render available states in README.rst.tpl
        entry: ./bin/render_readme
        language: system
        require_serial: true
        always_run: true
        pass_filenames: false
  - repo: https://github.com/myint/rstcheck
    rev: v6.2.0
    hooks:
      - id: rstcheck
        name: Check reST files using rstcheck
        exclude: 'docs/CHANGELOG.rst'
        additional_dependencies: [sphinx==7.2.6]
  - repo: https://github.com/saltstack-formulas/mirrors-rst-lint
    rev: v1.3.2
    hooks:
      - id: rst-lint
        name: Check reST files using rst-lint
        exclude: |
            (?x)^(
                docs/CHANGELOG.rst|
                docs/TOFS_pattern.rst|
                docs/CONTRIBUTING_DOCS.rst|
                docs/index.rst|
                docs/modules_.*|
                docs/pillar.rst|
                docs/README.rst|
                docs/toolsuite.rst|
                docs/states/.*
            )$
        additional_dependencies: [pygments==2.16.1]
