include:
  - .colors.clean
  - .doubleclick_title.clean
  - .hot_corners.clean
  - .live_text.clean
  - .locate_pointer.clean
  - .login_window_input_menu.clean
  - .scrollbar_jump_click.clean
  - .scrollbars_visibility.clean
  - .sidebar_iconsize.clean
  - .spotlight_index.clean
  - .tab_ui_elements.clean
  - .theme.clean
  - .toolbar_button_shapes.clean
  - .transparency_reduced.clean
  - .wallpaper_tinting.clean
  - .zoom_scroll_ui.clean
